datainsert/datainsert/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls',namespace="main")),
]

datainsert/main/urls.py
from django.urls import path

from . import views
app_name = "main"

urlpatterns = [
    path('', views.home, name="home"),
    path('data/', views.show, name="show"),
]

datainsert/main/models.py
from django.db import models

# Create your models here.


class Data(models.Model):
    name = models.CharField(max_length=255)
    contact = models.CharField(max_length=15)

    def __str__(self):
        return f"{self.name}-{self.contact}"

datainsert/main/views.py
from django.shortcuts import render
from django.contrib import messages
import random as rd
import string
from .models import Data
from django.core.paginator import Paginator
# Create your views here.


def gen_name(length):
    name = ''.join(rd.choices(string.ascii_uppercase, k=length))
    return name


def gen_contact(length):
    contact = ''.join([str(rd.randint(0, 9)) for _ in range(length)])
    return contact


def home(request):
    if request.method == "POST":
        number = int(request.POST['data-insert'])
        # print(number)
        insertcount = 0
        # name=namelist[rd.randint(0,len(namelist))]
        # contact="+91 "+str(rd.randint(1000000000,9999999999))
        # print(name,contact)
        if number > 0:
            try:
                for _ in range(number):
                    # name=rd.random(namelist)+rd.random(namelist)
                    name = gen_name(15)
                    contact = "+91 " + gen_contact(10)
                    # print(name,contact)
                    data = Data.objects.create(name=name, contact=contact)
                    data.save()
                    insertcount += 1
            except:
                messages.error(request, "Oops!! Some error occured."+str(insertcount) +
                               " data inserted.", extra_tags="alert alert-warning alert-dismissible fade show")
            messages.success(request, str(insertcount)+" data inserted successfully.",
                             extra_tags="alert alert-success alert-dismissible fade show")
        else:
            messages.error(request, "Please enter a valid value.",
                           extra_tags="alert alert-warning alert-dismissible fade show")
    return render(request, 'home.html')


def show(request):
    datas = Data.objects.all()
    paginator = Paginator(datas, 11)
    page = request.GET.get('page')
    datas = paginator.get_page(page)

    dict = request.GET.copy()
    params = dict.pop('page', True) and dict.urlencode()
    return render(request, 'showdata.html', {'datas': datas,'params':params})

datainsert/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>AI ASSIGNMENT</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <style>
      .wrapper {
        min-height: 80vh;
      }
    </style>        
  </head>
  <body>
    {% include 'navbar.html' %}
    <div class="wrapper">
      {% block content %}{% endblock content %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>        
  </body>
</html>

datainsert/templates/home.html
{% extends 'base.html' %}


{% block content %}
<div class="container d-flex flex-column justify-content-center my-4 flex-wrap">
    <div class="row center">
        <div class="col-md-6 offset-md-3">
            {% if messages %}
            <div class="messages">
                {% for message in messages %}
                <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
            </div>
            {% endif %}
            <form action="" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="data-insert">New data</label>
                    <input type="number" class="form-control" name="data-insert" placeholder="Enter the number of data to insert" required>
                </div>
                <button type="submit" class="btn btn-primary my-2">Insert</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

datainsert/templates/navbar.html
  <div class="container d-flex justify-content-center align-items-center flex-wrap">
  <!-- Nav for home page -->   
  <a class="btn btn-primary m-3" href="{% url 'main:home' %}" role="button">Home</a>
  <a class="btn btn-secondary m-3" href="{% url 'main:show' %}" role="button">Data</i></a>
  <!-- Nav for home page -->
 </div>

datainsert/templates/showdata.html
{% extends 'base.html' %}


{% block content %}


{% if datas %}
<div class="container d-flex justify-content-center flex-wrap my-4">
  <table class="table table-striped">
    <tr>
      <td>Name</td>
      <td>Contact no.</td>
    </tr>
    {% for data in datas %}
    <tr>
      <td>{{data.name}}</td>
      <td>{{data.contact}}</td>
    </tr>
    {% endfor %}
  </table>
  {% else %}
  <div style="height: 22rem;">
    <h1 class="text-center my-4">No data found</h1>
  </div>
  {% endif %}
</div>

<div class="container d-flex justify-content-center flex-wrap">
    <div class="mt-3">
      <ul class="pagination">
        {% if datas.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1&{{ params }}">First</a></li>
        <li class="page-item"><a class="page-link" href="?page={{ datas.previous_page_number }}&{{ params }}">Previous</a></li>
        {% endif %}
        
        <li class="page-item active"><a class="page-link" href="">{{ datas.number }}</a></li>
        
        {% if datas.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ datas.next_page_number }}&{{ params }}">Next</a></li>
        <li class="page-item"><a class="page-link" href="?page={{ datas.paginator.num_pages }}&{{ params }}">Last</a></li>
        {% endif %}
      </ul>
    </div>
</div>
{% endblock content %}
    